"""add puplisher

Revision ID: 18fe033622fa
Revises: 1c73cdbcfc29
Create Date: 2024-08-21 10:04:14.281297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fe033622fa'
down_revision: Union[str, None] = '1c73cdbcfc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_publisher'), 'books', ['publisher'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_publisher'), table_name='books')
    op.drop_column('books', 'publisher')
    # ### end Alembic commands ###
