"""access and refresstokens are edited

Revision ID: 3eefaa3011f5
Revises: 2c8d8dad25b4
Create Date: 2024-08-23 15:55:51.537273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eefaa3011f5'
down_revision: Union[str, None] = '2c8d8dad25b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('access_token', sa.String(), nullable=False))
    op.add_column('user_tokens', sa.Column('refresh_token', sa.String(), nullable=False))
    op.drop_column('user_tokens', 'refresh_key')
    op.drop_column('user_tokens', 'access_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('access_key', sa.VARCHAR(), nullable=False))
    op.add_column('user_tokens', sa.Column('refresh_key', sa.VARCHAR(), nullable=False))
    op.drop_column('user_tokens', 'refresh_token')
    op.drop_column('user_tokens', 'access_token')
    # ### end Alembic commands ###
