"""Remove unnecessary members column from Member tableand episodes

Revision ID: 62fc66ef8d9e
Revises: 0dfb7fa6d4ac
Create Date: 2024-08-28 05:09:49.191041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fc66ef8d9e'
down_revision: Union[str, None] = '0dfb7fa6d4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('is_full', sa.Boolean(), nullable=False))
    op.drop_column('episodes', 'is_active')
    op.drop_column('members', 'is_full')
    op.drop_column('members', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('members', sa.Column('is_full', sa.BOOLEAN(), nullable=False))
    op.add_column('episodes', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.drop_column('episodes', 'is_full')
    # ### end Alembic commands ###
