"""user table edited

Revision ID: a9f9d4453cbd
Revises: 3eefaa3011f5
Create Date: 2024-08-27 00:11:17.709523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f9d4453cbd'
down_revision: Union[str, None] = '3eefaa3011f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_author', table_name='books')
    op.drop_index('ix_books_id', table_name='books')
    op.drop_index('ix_books_name', table_name='books')
    op.drop_index('ix_books_publisher', table_name='books')
    op.drop_table('books')
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('no_of_khatmis', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'no_of_khatmis')
    op.drop_column('users', 'points')
    op.drop_column('users', 'profile_image')
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('publisher', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_books_publisher', 'books', ['publisher'], unique=False)
    op.create_index('ix_books_name', 'books', ['name'], unique=False)
    op.create_index('ix_books_id', 'books', ['id'], unique=False)
    op.create_index('ix_books_author', 'books', ['author'], unique=False)
    # ### end Alembic commands ###
